# Generated by Django 4.2.1 on 2023-05-12 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personne',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
